name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  rust-test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Check formatting of all crates in the workspace
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
      - name: Run cargo test --all
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all
      - name: Run cargo test --all-targets
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-targets
          
